apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  namespace: {{ .Values.serviceMesh.namespace.name }} 
  name: {{ .Values.serviceMesh.controlPlane.name }} 
spec:
  tracing:
    sampling: 10000
    type: Jaeger
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: {{ .Values.serviceMesh.controlPlane.addons.grafana.enabled | default "true" }} 
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: {{ .Values.serviceMesh.controlPlane.addons.kiali.enabled | default "true" }} 
    prometheus:
      enabled: {{ .Values.serviceMesh.controlPlane.addons.prometheus.enabled | default "true" }} 
  version: {{ .Values.serviceMesh.controlPlane.version }} 
  telemetry:
    type: Istiod
