apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/elasticsearch-operator.openshift-operators-redhat: ""
    operators.coreos.com/elasticsearch-operator.openshift-operators: ""
  namespace: openshift-operators
  name: elasticsearch-operator
spec:
  channel: stable-5.2
  installPlanApproval: Automatic
  name: elasticsearch-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
