apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/servicemeshoperator.openshift-operators: ""  
  name: {{ .Values.openshiftServiceMesh.operator.serviceMesh.subscription.name }} 
  namespace: openshift-operators
spec:
  channel: {{ .Values.openshiftServiceMesh.operator.serviceMesh.spec.channel}} 
  installPlanApproval: {{ .Values.openshiftServiceMesh.operator.serviceMesh.spec.installPlanApproval }} 
  name: {{ .Values.openshiftServiceMesh.operator.serviceMesh.spec.name }} 
  source: {{ .Values.openshiftServiceMesh.operator.serviceMesh.spec.source }} 
  sourceNamespace: {{ .Values.openshiftServiceMesh.operator.serviceMesh.spec.sourceNamespace}}  
