kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: {{ .Values.openshiftApplications.projetoGrupo.name }} 
  labels:
    maistra.io/member-of: {{ .Values.openshiftApplications.projetoInfra.name }} 
  annotations:
    istio-injection: enabled
    openshift.io/description: ''
    openshift.io/display-name: ''
spec:
  finalizers:
    - kubernetes
