NAME: ossm-apps
LAST DEPLOYED: Tue Apr  5 21:34:45 2022
NAMESPACE: projeto-apps
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
MANIFEST:
---
# Source: helm-apps/templates/deploy- order.yaml
apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: order
---
# Source: helm-apps/templates/deploy-product.yaml
apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    app: product
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: product
---
# Source: helm-apps/templates/deploy- order.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order
    version: v1
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
      version: v1
  template:
    metadata:
      labels:
        app: order
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/scheme: "http"
    spec:
      containers:
      - name: order
        image: quay.io/jpontes/order:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
# Source: helm-apps/templates/deploy-product.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: product
    version: v1
  name: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
      version: v1
  template:
    metadata:
      labels:
        app: product
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/scheme: "http"
    spec:
      containers:
      - name: product
        image: quay.io/jpontes/product:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
# Source: helm-apps/templates/gateway-istio.yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: observe-metrics-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
# Source: helm-apps/templates/project-projeto-apps.yaml
kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: projeto-apps 
  labels:
    maistra.io/member-of: projeto-infra-ossm 
  annotations:
    istio-injection: enabled
    openshift.io/description: ''
    openshift.io/display-name: ''
spec:
  finalizers:
    - kubernetes
---
# Source: helm-apps/templates/virtual-service-istio.yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: observe-metrics-vs
spec:
  hosts:
  - "*"
  gateways:
  - observe-metrics-gateway
  http:
  - match:
    - uri:
        exact: /spl50
    rewrite:
      uri: /spl50
    route:
    - destination:
        host: product
        port:
          number: 8080
  - match:
    - uri:
        exact: /order
    rewrite:
      uri: /order
    route:
    - destination:
        host: order
        port:
          number: 8080
  - match:
    - uri:
        exact: /rating
    rewrite:
      uri: /rating
    route:
    - destination:
        host: order
        port:
          number: 8080

