#Não esquecer de validar igualdade: values.yaml e /roterio-helm.txt
#var_project_infra_ossm: proderj-dit-infra-ossm
#var_project_grupo_apps: proderj-dss-apps

openshiftServiceMesh:
  operator:
    serviceMesh:
      subscription:
        name: servicemeshoperator
      spec:
        channel: stable
        installPlanApproval: Automatic 
        name: servicemeshoperator 
        source: redhat-operators 
        sourceNamespace: openshift-marketplace
    elasticSearch:
      subscription:
      spec:
    kiali:
      subscription:
      spec:
    jaeger:
      subscription:
      spec:
  instance:
    serviceMeshControlPlane:
      metadata:
        namespace: proderj-dit-infra-ossm
        name: basic
      spec:
        addons:
          grafana:
            enabled: true
          kiali:
            enabled: true
          prometheus:
            enabled: true
        version: v2.1
    serviceMeshMemberRoll:
      metadata:
        namespace: proderj-dit-infra-ossm
        name: default
      spec:
        members:
